### ISSUE TITLE
BEC Colors - create colors for, zones, subzones, etc. 

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/bec-explorer#12]

**Comment by joeyklee** [comment]
see merge #13 for the color changes

**Comment by joeyklee** [comment]
still need to add colors for subzones, phase, and others (e.g. elevation, precipitation, etc)

**Comment by cmahony** [comment]
joey and i discussed this on the phone. we only need to color by two levels of the hierarchy: BEC zone and BEC unit. Also, the color scheming should also include an option to color by climate variables. i.e., the dropdown is modified so that it lists "color by: BEC zone, BEC unit, elevation, mean annual temperature, mean annual precipitation, etc..."
