### ISSUE TITLE
Complete! 

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/bec-explorer#43]
# 🎉🎉🎉🎉

**Comment by cmahony** [comment]
@joeyklee, the functionality for this tool is great. super nice work, and i'm sure i have no idea of the programming gymnastics you did to make this happen. there are a few bugs that i would like to work out prior to sending out. for example, the BEC labels in the scatterplot are scrambled: wrong label in the wrong place, and many labels are duplicated (e.g. in a MATxMAP scatterplot there are two points labeled BWBSvk, one of which is definitely in the wrong place). if you are out of time to work on this, i am totally fine with us leaving it for a little while until there is a chance to iron out the kinks. i am available to discuss mid-day tomorrow if you have time.

**Comment by joeyklee** [comment]
@cmahony - good for catching the issue. Actually I think this arises because the points were too large and were overlapping. Notice some of the transparencies are different because of the overlap. I've reduced the size of the non-focal points to help with this. Let me know if this resolved the issue. Also if you click on a point in the scatterplot, the map will zoom to the selected unit.

**Comment by cmahony** [comment]
hey joey, 
the problem is still there. see the screen shot for the BWBSvk. this is a cold, wet, northern unit but the scatterpoint is warm and very dry; we would expect the okanagan valley units (PPxh1, BGxh1) in this location of the scatter. a cruise around the scatter reveals that none of the units seem where they should be. 

![image](https://cloud.githubusercontent.com/assets/17104005/16710446/55bd5554-45e3-11e6-908d-6a883fc05b8c.png)

it's not because of the log-transformation: 

![image](https://cloud.githubusercontent.com/assets/17104005/16710460/f93e058e-45e3-11e6-8699-f6731951bb66.png)

if the BWBSvk is set as the focal unit, its trajectory point shows up elsewhere. incidentally, this is where i would expect it to be in the scatter. 
![image](https://cloud.githubusercontent.com/assets/17104005/16710458/f3ef2428-45e3-11e6-8907-23af0cf2fc86.png)

if i set the focal and comparison units to okanagan valley units, the trajectories show up in the right place in the scatterplot, but the points underneath them are labelled wrong. 
![image](https://cloud.githubusercontent.com/assets/17104005/16710490/56b21e52-45e5-11e6-9dac-6dfd9845ac5e.png)

so it looks like the scatterpoints are just getting the wrong label for some reason.

**Comment by cmahony** [comment]
@joeyklee, in the bigger picture, i think we are missing a key step in the development of the beta version, in which we both give the tool a good kick, identify a bunch of issues, and then fix the problems we find. I've come across a few other issues that i think we need to fix before we send the tool out for feedback. I feel pretty strongly that we need a robust beta version that won't alienate our stakeholders with bugs and quirks. 

What i don't want is to put you in a time crunch. you are a week away from going to africa and i'm sure you have a bunch of other things to do. it's been a heroic effort on your part to get the tool to its current state in a very short period of time. i propose that we leave the beta version until you have a couple of days on your return to work out the bugs. i'm not in a hurry and in the meantime i could spend a few days getting the text pages in really good shape. what are your thoughts?

**Comment by joeyklee** [comment]
@cmahony Re the scatterpoints: maybe check again? I hadn't pushed the latest version up to heroku. It should be the latest one now

**Comment by joeyklee** [comment]
@cmahony Re other issues: Let's keep an open dialogue and keep posting issues in the issue tracker. If we're worried about bugs, we can also send it out to close friends to see if they come up with issues or things that don't work. Maybe a fresh set of eyes could be useful?

**Comment by joeyklee** [comment]
@cmahony - I think I solved the label misnaming issue. I dug into it and I think it had something to do with that the labels weren't updating each time the chart was updating, rather the labels were just being added over and over without removign the old labels.

**Comment by cmahony** [comment]
nice. it's looking great now.
