### ISSUE TITLE
Ensemble mean files for Scatterplot trajectories

### ISSUE THREAD

**Issue by cmahony** [joeyklee/bec-explorer#45]
@joeyklee, i'm not sure what values were used for the scatterplot trajectories, but they seem a bit weird. i have uploaded a csv file of 2071-2100 normals for the large ensemble (15 models) to dropbox: **BEC10centroid_EnsembleMean_2085_MSYT.csv**. these data will be consistent with the scatterplot data. 

Note that this file contains values for both RCPs, so perhaps you will want to split into two files for convenience. also note that this file is a subset of the BEC10centroid_99GCMs_MSYT.csv file already on dropbox. 

i will make sure that the plot descriptions adequately describe the data behind the trajectories.

**Comment by joeyklee** [comment]
@cmahony just a few notes:
- just to keep things consistent, it would be cool to reduce the amount of data format changes so we don't have to keep refactoring the code to match those changes. 
-  in this situation, it would then be helpful if either: 1. you split the data and then put the split data file to minimize the possibility of me messing it up since you're more familiar with the data or 2. specified a field name within the data that would indicate how the split should be done.

**Comment by cmahony** [comment]
i will split it and match the format. what was the file you were using for the trajectories?

**Comment by joeyklee** [comment]
I was just using: bec10centroid_access1_0_rcp45_2011_2100msyt

**Comment by cmahony** [comment]
ok. this was the wrong file to be using and explains the weird values. 
i will still split the file into the two RCPs, but it will inevitably in a different format: instead of time series, this is 2071-2100 normals, so there will be only one row of climate values for each BEC unit. 
will get you the new files asap (~10 min)

**Comment by joeyklee** [comment]
@cmahony actually - I can just use the ensemble mean data from the timeseries instead if that's ok with you?

**Comment by cmahony** [comment]
sure, that would be fine. just be sure to calculate and use the average of the years 2071-2100, rather than taking an individual year.
