### ISSUE TITLE
Sketch and wireframe bec prototype

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/bec-explorer#5]

**Comment by DiannaB42** [comment]
![climateselect](https://cloud.githubusercontent.com/assets/19374632/15765532/d8f7967a-2903-11e6-8e54-c70f464427cb.jpg)
![rangelocator](https://cloud.githubusercontent.com/assets/19374632/15765533/d8fdd512-2903-11e6-8178-3a2c01641536.jpg)

**Comment by joeyklee** [comment]
Awesome! Thanks so much @DiannaB42 - I hadn't even thought about doing a lookup via organism, but that could be a really neat way of selecting the BEC zones of interest. @cmahony - what do you think? 

There's also some really great work happening with the Science Fair Project (https://github.com/codeforscience/sciencefair) that in the super deluxe version of the BEC explorer, I could imagine doing searches on papers as well. Definitely something for the future, but nice to keep this idea in mind.

**Comment by joeyklee** [comment]
Hey ya'll: my wireframes are here - https://github.com/joeyklee/bec-explorer/blob/master/assets/wireframes/jlee-wireframes-001/jlee-wireframes-001.pdf

Happy to discuss anything - I will make some printouts for tomorrow. Would love your feedback when you get a chance @cmahony.

**Comment by cmahony** [comment]
Wow, i love these wireframes!!!!!!! I'll try to call in tomo morn but just in case i can't , here are a few comments. 
Diana, you've raised some great ideas here. I hadn't thought of a monthly normals plot e.g. http://www.permaculturenews.org/images/01-NOAA_monthly_climate_normals--graph.jpg But this would be great to have, especially if able to compare side by side with a second location to see relative differences. I could make one of thse for each BEC unit or we could embed the code to calculate the normals plot directly in the site?? 
I also like the idea of having some species-level info. We could start with tree species, for which there is great spatial data available. E.g. http://www.genetics.forestry.ubc.ca/cfcg/range-maps.html#rangemaps , 
Joey, i think you've nailed a great layout, with beautiful wireframes. There are quite a few details to discuss, such as log-tramsforming all zero-limited variables (like precip), what to have as fields in the photo entry area,etc.. But i think those are the details to iron out after the sprint, right?  One comment is that i think the primary bec unit should be the main selectable dropdown, instead of climate variable as in your wireframe. 
Thanks for a great day! Looking forward to checking in with you both tomorrow. Thanks a million diana!

**Comment by DiannaB42** [comment]
Glad that was useful. I was worried the data for habitats might not be in
the data set.

I won't be available until after 3 today unfortunately, but I will see you
then.
